"use client";

import { useState } from "react";
import { MemoView, type MemoDocument } from "@/components/memo-view";
import type { MemoInputs } from "@/lib/memo/build-inputs";

// The live memo control (B4, D3). After an upload is parsed and normalized, this
// posts the code-computed inputs to /api/memo, which calls an Opus-class model
// server-side (key never reaches the client) and returns a memo whose every
// dollar figure has been validated against the supplied inputs (control C2). The
// returned memo renders with the same MemoView as the cached hero.

interface MemoResponse {
  memo: MemoDocument;
  validation: { ok: boolean; flagged: number[] };
}

export function GenerateMemo({ inputs }: { inputs: MemoInputs }) {
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<MemoResponse | null>(null);

  async function generate() {
    setBusy(true);
    setError(null);
    setResult(null);
    try {
      const res = await fetch("/api/memo", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ action: "memo", inputs }),
      });
      const data = (await res.json()) as MemoResponse & { error?: string };
      if (!res.ok) {
        setError(data.error ?? "Could not generate the memo.");
        return;
      }
      setResult(data);
    } catch {
      setError("Network error. Please try again.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <section className="rounded-lg border border-hairline bg-surface shadow-card">
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-hairline px-5 py-4">
        <div>
          <h2 className="text-sm font-semibold tracking-tight text-ink">Live CFO memo</h2>
          <p className="mt-0.5 text-xs text-muted">
            Generated by an Opus-class model from the numbers above. The model writes
            the language; every figure is computed by code and validated (control C2).
          </p>
        </div>
        <button
          type="button"
          onClick={generate}
          disabled={busy}
          className="inline-flex items-center rounded-md bg-accent px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-accent-soft disabled:opacity-50"
        >
          {busy ? "Generating..." : result ? "Regenerate" : "Generate memo"}
        </button>
      </div>

      {error ? (
        <p className="px-5 py-3 text-sm text-risk" role="alert">{error}</p>
      ) : null}

      {result ? (
        <div className="px-5 py-5">
          <div className="mb-4 flex items-center gap-2">
            {result.validation.ok ? (
              <span className="inline-flex items-center rounded-sm border border-positive/40 bg-positive-wash px-2 py-0.5 text-[11px] font-semibold uppercase tracking-[0.12em] text-positive">
                All figures verified
              </span>
            ) : (
              <span className="inline-flex items-center rounded-sm border border-caution/40 bg-caution-wash px-2 py-0.5 text-[11px] font-semibold uppercase tracking-[0.12em] text-caution">
                {result.validation.flagged.length} figure(s) withheld
              </span>
            )}
            <span className="text-xs text-faint">Control C2: every dollar figure traces to a computed input.</span>
          </div>
          <MemoView memo={result.memo} />
        </div>
      ) : null}
    </section>
  );
}
